
export const SET_USER_IDENTITY = 'SET_USER_IDENTITY';
export const SET_ROOM_ID = 'SET_ROOM_ID';
export const SET_CELL_VALUE = 'SET_CELL_VALUE';
export const LEFT_CURRENT_GAME_ROOM = 'LEFT_CURRENT_GAME_ROOM';

